version: '3.7'
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: newsparser
  php:
    build: ./docker/php
    volumes:
    - ./:/app
  nginx:
    image: nginx:alpine
    ports:
    - "8080:8080"
    volumes:
    - ./:/app
    - ./var/log/nginx:/var/log/nginx
    - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php
    working_dir: /app
